---
title: "Elliptic Curves"
date: "2016-05-25"
description: "Elliptic curves with complex multiplication give rise to tori over the complex numbers"
categories: [mathematics, 3d printing, autodesk maya]
---

### Elliptic curves with complex multiplication give rise to tori over the complex numbers  

Completed in spring 2016 at the [Mathematical Computing Laboratory](http://mcl.math.uic.edu/) at UIC.  

This [repository](https://github.com/galenballew/Elliptic-Curves) contains the paper, poster, images, and 3d modeling files from my research and learning project on elliptic curves. I completed this project with James
Duncan under the guidance of Cara Mullen (PhD) and Professor Alina Cojocaru (PhD).

<a markdown="0" href="https://github.com/galenballew/Elliptic-Curves/blob/master/arithmetic_EC.pdf" class="btn">Download Paper</a><br></br>
<a markdown="0" href="https://github.com/galenballew/Elliptic-Curves/blob/master/496%20Poster/MCL-poster.pdf" class="btn">Download Poster</a><br></br>


### Summary 
Our research focuses on elliptic curves $E over $Q with complex
multiplication (by the maximal order of an imaginary quadratic
field). Viewed over $C, each $E gives rise to two tori, defined by
the generators $\omega_1 and $\omega_2 of the period lattice. These tori can be
constructed virtually into a 3D mesh. Further, this mesh can be
translated into gcode and printed using a 3D printer.
<br></br>
<br></br>

<p align="center">
<iframe width="560" height="315" src="https://www.youtube.com/embed/UeLQxoG2wNY" frameborder="0" allowfullscreen></iframe>
</p>
