project:
  type: website

website:
  title: "Galen Ballew"
  navbar:
    right:
      - text: "About Galen"
        file: about.qmd
      - text: "Resume"
        file: "static/ballew_resume_2021.pdf"
      - icon: github
        href: https://github.com/galenballew
      - icon: linkedin
        href: https://linkedin.com/in/galenballew
      - icon: envelope-at
        href: mailto:galenballew@gmail.com
  favicon: /static/favicon.png
format:
  html:
    theme:
      dark: slate
      light: spacelab
    css: styles.css



